name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t your-dockerhub-username/nginx-app .
          docker tag your-dockerhub-username/nginx-app your-dockerhub-username/nginx-app:latest
          docker push your-dockerhub-username/nginx-app:latest
